version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: spomatcher_development
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/spomatcher
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    environment: 
      - GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY

volumes:
  mysql-data:
  bundle: