version: 2.1

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.6.47
        environment:
          BUNDLER_VERSION: 2.1.4
          MYSQL_ARROW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
    working_directory: ~/projects/spomatcher
    steps:
      - checkout
      - run: gem install bundler -v 2.1.4
      - run: bundle config set path 'vendor/bundle'
      - run: yarn install
      - run: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop 

  rspec:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.6.47
        environment:
          BUNDLER_VERSION: 2.1.4
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_DB: spomatcher_test
    working_directory: ~/projects/spomatcher
    steps:
      - checkout
      - run: gem install bundler -v 2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          BUNDLER_VERSION: 2.1.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "40:0a:81:f8:f5:dd:09:bf:88:af:2a:c0:26:b3:f3:94"
      - run: gem install bundler -v 2.1.4
      - run: bundle install
      - deploy:
          name: Capistrano deploy
          command:
            bundle exec cap production deploy

workflows:
  version: 2
  rubocop_rspec_deploy:
    jobs:
      # - rubocop
      # - rspec:
      #     requires:
      #       - rubocop
      - deploy
          # requires:
          #   - rspec
          # filters:
          #   branches:
          #     only: master